# Generated by Django 2.2.2 on 2020-10-03 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingTable',
            fields=[
                ('Tender_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=20)),
                ('Bid_Amount_Ksh', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingTenders',
            fields=[
                ('Tender_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Vendors_Name', models.CharField(max_length=20)),
                ('Project_Name', models.CharField(max_length=20)),
                ('Project_Type', models.CharField(max_length=50)),
                ('Basic_Amount_Ksh', models.IntegerField()),
                ('Bid_Close_Date', models.DateTimeField(verbose_name='date closed')),
                ('Tender_Type', models.CharField(max_length=20)),
                ('Project_file', models.CharField(max_length=20)),
                ('Bid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VendorsTable',
            fields=[
                ('Tender_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=50)),
                ('Bid_Amount_Ksh', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('Accept', models.CharField(max_length=20)),
                ('Reject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('address', models.IntegerField(default=0)),
                ('mail', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactTable',
            fields=[
                ('Number', models.AutoField(primary_key=True, serialize=False)),
                ('Vendor_Name', models.CharField(max_length=20)),
                ('Mobile_No', models.IntegerField()),
                ('Mail_Id', models.CharField(max_length=20)),
                ('Address', models.IntegerField()),
                ('upcomingtenders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmcs.UpcomingTenders')),
            ],
        ),
        migrations.CreateModel(
            name='BiddingStatusTable',
            fields=[
                ('Tender_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Project_Name', models.CharField(max_length=20)),
                ('Bid_Amount_Ksh', models.IntegerField()),
                ('Name', models.CharField(max_length=20)),
                ('Status', models.CharField(max_length=20)),
                ('vendorstable', models.ManyToManyField(to='bmcs.VendorsTable')),
            ],
        ),
    ]
