# Generated by Django 2.1 on 2020-10-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingtenders',
            name='description',
            field=models.CharField(blank=True, default='0000000', max_length=255),
        ),
        migrations.AddField(
            model_name='upcomingtenders',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
