# Generated by Django 2.1 on 2020-10-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmcs', '0004_auto_20201018_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcomingtenders',
            name='Project_file',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='upcomingtenders',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
