# Generated by Django 2.1 on 2020-10-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmcs', '0007_auto_20201018_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddingstatustable',
            name='Tender_Id',
        ),
        migrations.RemoveField(
            model_name='biddingtable',
            name='Tender_Id',
        ),
        migrations.RemoveField(
            model_name='vendorstable',
            name='Tender_Id',
        ),
        migrations.AddField(
            model_name='biddingstatustable',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='biddingtable',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorstable',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
