# Generated by Django 2.1 on 2020-10-18 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmcs', '0008_auto_20201018_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacttable',
            name='upcomingtenders',
        ),
        migrations.DeleteModel(
            name='ContactTable',
        ),
    ]
