# Generated by Django 2.1 on 2020-10-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmcs', '0010_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='post',
            new_name='tender',
        ),
    ]
